import type { GenerationMode } from "@/lib/constants";

export type OutputTemplate = {
  mode: GenerationMode;
  label: string;
  description: string;
  requiredSections: string[];
  toneDefaults: string[];
  exampleOutline: string;
};

export const OUTPUT_TEMPLATES: Record<GenerationMode, OutputTemplate> = {
  one_pager: {
    mode: "one_pager",
    label: "One Pager",
    description: "Client-friendly one page campaign summary.",
    requiredSections: [
      "Objective",
      "Target Audience",
      "Key Message",
      "Big Idea",
      "Deliverables",
      "Channels",
      "Timeline",
      "KPIs",
    ],
    toneDefaults: ["clear", "executive", "client-ready"],
    exampleOutline: [
      "# Campaign One-Pager",
      "## Objective",
      "## Target Audience",
      "## Key Message",
      "## Big Idea",
      "## Deliverables",
      "## Channels",
      "## Timeline",
      "## KPIs",
    ].join("\n"),
  },
  expand: {
    mode: "expand",
    label: "Expand",
    description: "Full concept expansion with execution detail.",
    requiredSections: [
      "Big Idea",
      "Why It Spreads",
      "Execution Steps",
      "Required Assets",
      "Channels & Distribution",
      "Timeline",
      "Risks & Mitigations",
      "KPIs",
    ],
    toneDefaults: ["strategic", "pragmatic", "insightful"],
    exampleOutline: [
      "# Big Idea",
      "## Why It Spreads",
      "## Execution Steps",
      "## Required Assets",
      "## Channels & Distribution",
      "## Timeline",
      "## Risks & Mitigations",
      "## KPIs",
    ].join("\n"),
  },
  alternatives: {
    mode: "alternatives",
    label: "Alternatives",
    description: "Five distinct creative directions.",
    requiredSections: ["A", "B", "C", "D", "E"],
    toneDefaults: ["diverse", "creative", "comparative"],
    exampleOutline: [
      "# Alternative Directions",
      "## A — [Title]",
      "- Rationale",
      "## B — [Title]",
      "- Rationale",
      "## C — [Title]",
      "- Rationale",
      "## D — [Title]",
      "- Rationale",
      "## E — [Title]",
      "- Rationale",
    ].join("\n"),
  },
  virality: {
    mode: "virality",
    label: "Virality",
    description: "Hooks, share triggers, and remix ideas.",
    requiredSections: [
      "Improved Hooks & Angles",
      "10 Hooks",
      "3 Share Triggers",
      "Remix Ideas",
    ],
    toneDefaults: ["sharp", "social-first", "punchy"],
    exampleOutline: [
      "# Virality Boost Plan",
      "## Improved Hooks & Angles",
      "## 10 Hooks",
      "## 3 Share Triggers",
      "## Remix Ideas",
    ].join("\n"),
  },
  pitch_outline: {
    mode: "pitch_outline",
    label: "Pitch Outline",
    description: "Slide-by-slide pitch deck outline.",
    requiredSections: [
      "Title & Big Idea",
      "Problem",
      "Insight",
      "The Idea",
      "How It Works",
      "Channel Strategy",
      "Content & Assets",
      "Timeline",
      "KPIs",
      "Budget & Next Steps",
    ],
    toneDefaults: ["structured", "client-facing", "concise"],
    exampleOutline: [
      "# Pitch Deck Outline",
      "## Slide 1 — Title & Big Idea",
      "## Slide 2 — The Problem",
      "## Slide 3 — The Insight",
      "## Slide 4 — The Idea",
      "## Slide 5 — How It Works",
      "## Slide 6 — Channel Strategy",
      "## Slide 7 — Content & Assets",
      "## Slide 8 — Timeline",
      "## Slide 9 — KPIs",
      "## Slide 10 — Budget & Next Steps",
    ].join("\n"),
  },
  ugc_scripts: {
    mode: "ugc_scripts",
    label: "UGC Scripts",
    description: "Five UGC concepts with scripts and shot lists.",
    requiredSections: ["Concepts 1-5", "Hook", "Script", "Shot List", "Captions", "CTA"],
    toneDefaults: ["creator-style", "fast", "authentic"],
    exampleOutline: [
      "# UGC Scripts",
      "## Concept 1",
      "- Hook",
      "- Script",
      "- Shot List",
      "- Captions",
      "- CTA",
      "## Concept 2",
      "- Hook",
      "- Script",
      "- Shot List",
      "- Captions",
      "- CTA",
      "## Concept 3",
      "- Hook",
      "- Script",
      "- Shot List",
      "- Captions",
      "- CTA",
      "## Concept 4",
      "- Hook",
      "- Script",
      "- Shot List",
      "- Captions",
      "- CTA",
      "## Concept 5",
      "- Hook",
      "- Script",
      "- Shot List",
      "- Captions",
      "- CTA",
    ].join("\n"),
  },
  storyboard: {
    mode: "storyboard",
    label: "Storyboard",
    description: "Storyboard beats with shot list and VO.",
    requiredSections: ["Frames", "Shot List", "Voiceover"],
    toneDefaults: ["visual", "cinematic", "clear"],
    exampleOutline: [
      "# Storyboard",
      "## Frames (8–12 beats)",
      "## Shot List",
      "## Voiceover / Copy",
    ].join("\n"),
  },
  press_release: {
    mode: "press_release",
    label: "Press Release",
    description: "PR-style announcement for internal or external use.",
    requiredSections: ["Headline", "Summary", "Key Details", "Quote", "Call to Action"],
    toneDefaults: ["press-ready", "formal", "confident"],
    exampleOutline: [
      "# Press Release",
      "## Headline",
      "## Summary",
      "## Key Details",
      "## Quote",
      "## Call to Action",
    ].join("\n"),
  },
  faq: {
    mode: "faq",
    label: "FAQ",
    description: "Internal FAQ for launch and stakeholder alignment.",
    requiredSections: ["FAQ"],
    toneDefaults: ["clear", "direct", "internal"],
    exampleOutline: [
      "# Campaign FAQ",
      "## Q: ...",
      "- A: ...",
    ].join("\n"),
  },
};

export const OUTPUT_TEMPLATE_LIST = Object.values(OUTPUT_TEMPLATES);
